apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: network-policies
  namespace: openshift-gitops
spec:
  destination:
    name: in-cluster
    namespace: openshift-gitops
  source:
    targetRevision: HEAD
    repoURL: https://git.borsaistanbul.com/...../..../.....git
    path: values/platform/networkPolicies
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
  project: default