apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: quasys-test-app1
  namespace: argocd
spec:
  destination:
    name: in-cluster
    namespace: argocd-testapps
  source:
    targetRevision: HEAD
    repoURL: https://github.com/emreyardimci/argocd-appinap.git
    path: values/quasys-test-app1
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      force: true
  project: default